apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-api
  namespace: aegis
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: aegis-api
  template:
    metadata:
      labels:
        app: aegis-api
    spec:
      containers:
        - name: aegis-api
          image: fierynxx/aegis-api:806352d
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: api-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: aegis-api-svc
  namespace: aegis
spec:
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  selector:
    app: aegis-api
