---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: aegis-api
  namespace: aegis
spec:
  parentRefs:
    - name: main-gateway
      namespace: default
  hostnames:
    - "api.aegis.web.id"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: aegis-api-svc
          port: 8001
